#! /bin/bash

docker-compose down -v
docker-compose up -d --build

echo "--------------------------------- RUNNING TESTS ---------------------------------"
docker exec DrTrottoir-be-d python manage.py test
docker exec DrTrottoir-fe-d npm run jest:workflow

echo "--------------------------------- RUNNING LINTERS ---------------------------------"
docker exec DrTrottoir-be-d flake8 backend/ drtrottoir/
docker exec DrTrottoir-fe-d npm run lint