version: '3.8'

services:
  django:
    build:
      dockerfile: Dockerfile.prod
      context: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  next:
    build:
      dockerfile: Dockerfile.prod
      context: frontend
      target: runner
    command: npm run start
    ports:
      - 3000:3000
    env_file:
      - .env.prod.db
    depends_on:
      - django
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - django
      - next

volumes:
  postgres_data:
  static_volume: