version: '3.8'

services:
  django:
    container_name: DrTrottoir-be
    build:
      dockerfile: Dockerfile.prod
      context: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/uploads
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always
  db:
    container_name: DrTrottoir-db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    restart: always
  next:
    container_name: DrTrottoir-fe
    build:
      dockerfile: Dockerfile.prod
      context: frontend
      target: runner
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - django
    env_file:
      - .env.prod
  nginx:
    container_name: DrTrottoir-nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - /etc/letsencrypt:/etc/nginx/ssl/
      - ./certbot-webroot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
      - next
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
