version: '3.8'

services:
  django:
    container_name: DrTrottoir-be-d
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
  db:
    container_name: DrTrottoir-db-d
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=drtrottoir_dev
      - POSTGRES_PASSWORD=foo
      - POSTGRES_DB=drtrottoir_dev
  next:
    container_name: DrTrottoir-fe-d
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env.dev
volumes:
  postgres_data: