# Generated by Django 4.1.7 on 2023-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='short name for building')),
                ('address', models.CharField(max_length=255, verbose_name='building address')),
                ('description', models.CharField(max_length=4095, verbose_name='building description')),
            ],
        ),
    ]
