# Generated by Django 4.1.7 on 2023-03-05 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='short name for building')),
                ('description', models.CharField(max_length=4095, verbose_name='building description')),
                ('name', models.CharField(max_length=256, verbose_name='name of building')),
                ('manual', models.FileField(upload_to='files/', verbose_name='manual')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256, verbose_name='street')),
                ('number', models.CharField(max_length=10, verbose_name='house number')),
                ('zip_code', models.IntegerField(verbose_name='zip code')),
                ('city', models.CharField(max_length=256, verbose_name='cityname')),
                ('country', models.CharField(max_length=256, verbose_name='countryname')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='default', max_length=256, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='default', max_length=256, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(verbose_name='time of arrival')),
                ('comment', models.TextField(blank=True, verbose_name='Comment on the visit')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building', verbose_name='id of building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id of user')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name of the tour')),
                ('version', models.IntegerField(verbose_name='version of the tour')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.location', verbose_name='location of the tour')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of the schedule')),
                ('comment', models.TextField(blank=True, verbose_name='comment on the scheduled tour')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id of user')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.tour', verbose_name='id of the scheduled tour')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Arrival'), (2, 'Departure'), (3, 'Extra')], verbose_name='type of photo')),
                ('comment', models.TextField(verbose_name='comment on the photo')),
                ('created_at', models.DateTimeField(verbose_name='time of creation')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building', verbose_name='id of visit')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingInTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(verbose_name='order index of the building in the tour')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building', verbose_name='id of building')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.tour', verbose_name='id of tour')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.location', verbose_name='adress of building'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='buildings',
            field=models.ManyToManyField(null=True, to='drtrottoir.building'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.location', verbose_name='address of the user'),
        ),
    ]
