# Generated by Django 4.1.7 on 2023-03-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0003_alter_building_manual_alter_customuser_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=256, verbose_name='name of the region')),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='version',
        ),
        migrations.AddField(
            model_name='building',
            name='address_line_1',
            field=models.CharField(default='', max_length=256, verbose_name='address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='address_line_2',
            field=models.CharField(default='', max_length=256, verbose_name='address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='country',
            field=models.CharField(default='', max_length=256, verbose_name='countryname'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='drtrottoir.region', verbose_name='region of building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drtrottoir.region', verbose_name='address of the user'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='drtrottoir.region', verbose_name='region of the tour'),
            preserve_default=False,
        ),
    ]
