# Generated by Django 4.1.7 on 2023-03-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0004_region_remove_building_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='region_name',
        ),
    ]
