# Generated by Django 4.1.7 on 2023-03-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0004_region_remove_building_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region',
        ),
        migrations.AddField(
            model_name='region',
            name='region_name',
            field=models.CharField(default='', max_length=256, unique=True, verbose_name='name of the region'),
            preserve_default=False,
        ),
    ]
