# Generated by Django 4.1.7 on 2023-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0007_remove_building_name_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='superstudent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='superuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Developer'), (2, 'Superadmin'), (3, 'Superstudent'), (4, 'Owner'), (5, 'Student')], default=5),
        ),
    ]
