# Generated by Django 4.1.7 on 2023-03-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0007_remove_building_name_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of waste collection')),
                ('waste_type', models.CharField(max_length=256, verbose_name='Type of waste')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building', verbose_name='building of waste collection')),
            ],
        ),
    ]
