# Generated by Django 4.1.7 on 2023-03-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0009_alter_customuser_buildings_alter_customuser_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='building',
        ),
        migrations.AddField(
            model_name='visit',
            name='building_in_tour',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.buildingintour', verbose_name='id of building'),
            preserve_default=False,
        ),
    ]
