# Generated by Django 4.1.7 on 2023-03-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0008_waste'),
        ('drtrottoir', '0009_alter_customuser_buildings_alter_customuser_region'),
    ]

    operations = [
    ]
