# Generated by Django 4.1.7 on 2023-03-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0009_alter_customuser_buildings_alter_customuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.visit', verbose_name='id of visit'),
        ),
    ]
