# Generated by Django 4.1.7 on 2023-03-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0010_remove_visit_building_visit_building_in_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='building_in_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.buildingintour', verbose_name='id of building in tour'),
        ),
    ]
