# Generated by Django 4.1.7 on 2023-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0010_alter_photo_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
