# Generated by Django 4.1.7 on 2023-04-13 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0015_alter_customuser_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='drtrottoir.schedule', verbose_name='schedule linked to visit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waste',
            name='action',
            field=models.CharField(default=0, max_length=256, verbose_name='Action required'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingintour',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drtrottoir.building', verbose_name='id of building'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='id of user'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='id of user'),
        ),
    ]
