# Generated by Django 4.1.7 on 2023-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0017_alter_photo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(null=True)),
                ('cc', models.TextField(null=True)),
                ('bcc', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
