# Generated by Django 4.1.7 on 2023-04-28 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0018_remove_schedule_comment_remove_visit_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='time of last update')),
                ('text', models.TextField(verbose_name='Comment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building', verbose_name='building commented')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.schedule', verbose_name='schedule commented')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user who wrote comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='time of last update')),
                ('text', models.TextField(verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user who wrote comment')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.visit', verbose_name='visit commented')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
