# Generated by Django 4.1.7 on 2023-04-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0018_remove_schedule_comment_remove_visit_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drtrottoir.comment')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.visit', verbose_name='visit commented')),
            ],
            bases=('drtrottoir.comment',),
        ),
        migrations.CreateModel(
            name='ScheduleComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drtrottoir.comment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building', verbose_name='building commented')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.schedule', verbose_name='schedule commented')),
            ],
            bases=('drtrottoir.comment',),
        ),
    ]
