# Generated by Django 4.1.7 on 2023-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0020_alter_schedulecomment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.TextField(null=True, verbose_name='comment on the photo'),
        ),
    ]
