# Generated by Django 4.1.9 on 2023-05-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0022_customuser_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.schedule', verbose_name='schedule linked to visit'),
        ),
    ]
