# Generated by Django 4.1.9 on 2023-05-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0023_alter_visit_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(blank=True, default='')),
                ('cc', models.TextField(blank=True, default='')),
                ('bcc', models.TextField(blank=True, default='')),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
            ],
        ),
    ]
