name: ESLint CI

on:
  - push

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:

      # Check out the repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      # Install your dependencies
      - name: Install your dependencies
        working-directory: ./frontend
        run: npm ci

      # Run ESLint
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint