name: flake8 Lint

on:
  push:
    # branches:
    #   - main
    paths:
      - 'backend/backend/**/*.py'
      - 'backend/drtrottoir/**/*.py'


jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length=120
