name: "Tests CI"
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the image
        run: docker-compose up -d --build
      - name: Test Django unittest
        run: docker exec DrTrottoir-be python manage.py test
      - name: Test NEXT.js Jest
        run: docker exec DrTrottoir-fe npm run test