name: "Tests CI"
on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: sudo docker-compose up -d --build
      - name: Test Django unittest
        run: sudo docker exec -it DrTrottoir-be python manage.py test
      - name: Test NEXT.js Jest
        run: sudo docker exec -it DrTrottoir-fe npm run test