name: "Tests CI"
on:
  - push

jobs:
  jobname:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker-compose up -d --build
      - name: Test Django unittest
        run: docker exec -it DrTrottoir-be python manage.py test
      - name: Test NEXT.js Jest
        run: docker exec -it DrTrottoir-fe npm run test